using UnityEngine;

/// <summary>
/// Centralized input manager. Implements the Singleton pattern to eliminate duplicate PlayerControls instances.
/// </summary>
public class InputManager : MonoBehaviour
{
    /// <summary>A global instance of the input manager.</summary>
    public static InputManager Instance { get; private set; }

    /// <summary>An instance of the autogenerated Unity input system class.</summary>
    public PlayerControls Controls { get; private set; }

    /// <summary>
    /// Unity lifecycle method. Initializes a Singleton and creates an input control object.
    /// </summary>
    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }
        Instance = this;
        Controls = new PlayerControls();
        DontDestroyOnLoad(gameObject);
    }

    /// <summary>Enables input tracking when an object is activated.</summary>
    private void OnEnable() => Controls.Enable();

    /// <summary>Disables input tracking when deactivating an object.</summary>
    private void OnDisable() => Controls.Disable();
}